### ISSUE TITLE
Support for async functions

### ISSUE THREAD

**Issue by joelstevick** [marc-ed-raffalli/declarative-test-structure-generator#5]
I really like this module.  Nice work!   I am needing something like this, so I was about to write one of these, myself.   But, then I thought to myself "better check if one of these already exists."

Question: can hooks and test functions be async?

Thanks!
Joel

**Comment by joelstevick** [comment]
Hi Marc-Ed,

I have test functions (think: the arrow functions that implement an "it" test in a describe-block).  Most of the test frameworks will allow you to return a promise (async) and the test framework will wait for the promise to be resolved -- this is an alternative to the done-pattern...

Thanks!
Joel



________________________________

**Comment by joelstevick** [comment]
Hi Marc-Ed,

I have a suggestion for a feature that would make this module become quite compelling; and would enable my team to adopt your module as part of our devops.

It would be quicker and easier to describe using zoom and screen sharing...if you are open to it.

Also, I would be willing to implement the feature and then submit a PR to you, so you wouldn't have to build this yourself -- all I would ask is a speedy turnaround on the PR.

Let me know, and we can set up a zoom conference.

Joel

________________________________

**Comment by joelstevick** [comment]
Hi Marc-Ed,

Actually, I have decided to just create my own npm module that implements my idea, and leverages (not reproduces) the fine work that you have done.   And by the way, I forked your repo: what a masterpiece of clean code!

I will let you know when my npm module is published.   I think that our 2 modules when used together could really help improve the testing experience for developers.

Thanks,
Joel
Happy Easter!

________________________________

**Comment by marc-ed-raffalli** [comment]
Hi Joel,

I'm pretty sure the feature you mentioned should be supported as the package is only a high level wrapper.
I actually mis-read your message yesterday, I thought you were talking about the e2e package which is leveraging this one.

Drop me an email on raffalli.marc.ed@gmail.com and we can discuss.

Happy Easter!

**Comment by marc-ed-raffalli** [comment]
Hi Joel,

Closing this one for now, feel free to ping me or reopen if you have any issues :)

Thanks,
/Marc
